language: r
sudo: false
cache: packages
pandoc_version: 1.19.2.1
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - release
  - devel
  - oldrel

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      compiler: gcc
      r: release
      addons:
        apt:
          packages:
            - valgrind
      r_check_args: '--ignore-vignettes --as-cran --use-valgrind'
      r_build_args: '--no-build-vignettes'
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      r_github_packages:
        - jimhester/covr
      after_success:
        - Rscript -e 'covr::codecov()'
    - os: linux
      r: release
      compiler: clang
      before_install:
        - tlmgr install fontaxes sttools mweights libertine mathalfa
      r_build_args:
        - '--compact-vignettes=both'
    - os: osx
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

notifications:
  email:
    on_success: change
    on_failure: change
