language: r
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      r: release
      compiler: clang
      addons:
        apt:
          packages:
            - valgrind
      r_check_args: '--ignore-vignettes --use-valgrind'
      r_build_args: '--no-build-vignettes'
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

    - os: linux
      r: devel
      compiler: gcc
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      r: oldrel
      compiler: gcc

    - os: osx
      r: release

    - os: osx
      r: oldrel

notifications:
  email:
    on_success: change
    on_failure: change
