language: r
sudo: false
cache: packages
pandoc_version: 1.19.2.1
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      r: release
      addons:
        apt:
          packages:
            - valgrind
      r_check_args: '--ignore-vignettes --as-cran --use-valgrind'
      r_build_args: '--no-build-vignettes'
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      r_github_packages:
        - jimhester/covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      dist: trusty
      compiler: gcc
      r: devel
      r_build_args: '--compact-vignettes=both'
      before_install:
        - tlmgr install fontaxes sttools mweights libertine mathalfa

    - os: linux
      dist: trusty
      compiler: clang
      r: release
      r_build_args: '--compact-vignettes=both'
      before_install:
       - tlmgr install fontaxes sttools mweights libertine mathalfa

    - os: linux
      dist: trusty
      r: devel
      compiler: clang
      r_build_args: '--compact-vignettes=both'
      before_install:
        - tlmgr install fontaxes sttools mweights libertine mathalfa

    - os: linux
      r: oldrel
      r_build_args: '--compact-vignettes=both'
      before_install:
        - tlmgr install fontaxes sttools mweights libertine mathalfa

    - os: osx
      r: release
      latex: false
      osx_image: xcode8.3
      before_install:
        - curl -O http://r.research.att.com/libs/clang-4.0.0-darwin15.6-Release.tar.gz
        - tar fvxz clang-4.0.0-darwin15.6-Release.tar.gz -C /
        - cat <<- EOF > ~/.R/Makevars
        - CC=/usr/local/clang4/bin/clang
        - CXX=/usr/local/clang4/bin/clang++
        - CXX1X=/usr/local/clang4/bin/clang++
        - CXX98=/usr/local/clang4/bin/clang++
        - CXX11=/usr/local/clang4/bin/clang++
        - CXX14=/usr/local/clang4/bin/clang++
        - CXX17=/usr/local/clang4/bin/clang++
        - LDFLAGS=-L/usr/local/clang4/lib
        - EOF
        - xcode-select --install
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

notifications:
  email:
    on_success: change
    on_failure: change
