language: r
sudo: false
cache: packages
pandoc_version: 1.19.2.1
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
      r: release
      addons:
        apt:
          packages:
            - valgrind
      r_check_args: '--ignore-vignettes --as-cran --use-valgrind'
      r_build_args: '--no-build-vignettes'
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      r_github_packages:
        - jimhester/covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      dist: precise
      compiler: gcc
      r: devel
      r_build_args: '--compact-vignettes=both'
      before_install:
        - tlmgr install fontaxes sttools preprint mweights libertine mathalfa

    - os: linux
      dist: precise
      compiler: clang
      r: release
      r_build_args: '--compact-vignettes=both'
      before_install:
       - tlmgr install fontaxes sttools preprint mweights libertine mathalfa

    - os: linux
      dist: trusty
      r: devel
      compiler: clang
      r_build_args: '--compact-vignettes=both'
      before_install:
        - tlmgr install fontaxes sttools preprint mweights libertine mathalfa

    - os: linux
      r: oldrel
      r_build_args: '--compact-vignettes=both'
      before_install:
        - tlmgr install fontaxes sttools preprint mweights libertine mathalfa

    - os: osx
      r: release
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

notifications:
  email:
    on_success: change
    on_failure: change
